# classification

In [2]:
import pandas as pd

In [18]:
data={
"hour_studied":[1,2,3,4,5,6,7,8,9,10],
"passed":[0,0,0,0,0,1,1,1,1,1]
     }

In [19]:
df=pd.DataFrame(data)

In [20]:
df

   hour_studied  passed
0             1       0
1             2       0
2             3       0
3             4       0
4             5       0
5             6       1
6             7       1
7             8       1
8             9       1
9            10       1

In [24]:
# separate input and output

In [21]:
X=df[['hour_studied']]
y=df[['passed']]

In [22]:
X

   hour_studied
0             1
1             2
2             3
3             4
4             5
5             6
6             7
7             8
8             9
9            10

In [23]:
y

   passed
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       1
8       1
9       1

In [25]:
import sklearn
print(sklearn.__version__)

1.7.2

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
print(X_train)

   hour_studied
5             6
0             1
7             8
2             3
9            10
4             5
3             4
6             7

In [29]:
print(X_test)

   hour_studied
8             9
1             2

In [30]:
print(y_train)

   passed
5       1
0       0
7       1
2       0
9       1
4       0
3       0
6       1

In [31]:
print(y_test)

   passed
8       1
1       0

In [38]:
# import logistic regression

In [39]:
 from sklearn.linear_model import LogisticRegression

In [40]:
# Create and Train model

In [41]:
model=LogisticRegression()

In [43]:
model.fit(X_train,y_train)

C:\Users\Sakshi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [44]:
# prediction

In [45]:
y_pred=model.predict(X_test)

In [62]:
y_pred

array([1, 0])

In [47]:
X_test

   hour_studied
8             9
1             2

In [63]:
y_test

   passed
8       1
1       0

In [55]:
new_hours=pd.DataFrame({"hour_studied":[7.5]})

In [56]:
new_hours

   hour_studied
0           7.5

In [57]:
predicted_passing=model.predict(new_hours)

In [58]:
predicted_passing

array([1])

In [59]:
# accuracy score calculation

In [65]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [66]:
y_test

   passed
8       1
1       0

In [69]:
y_prob=model.predict_proba(X_test)

In [70]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])